<a href="https://colab.research.google.com/github/Srushti-01/Collaboratories/blob/main/Problem_sheet_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Question 1:A survey found that 65% of all financial customers were very satisfied with their primary
financial institution. Suppose that 25 financial customers are sampled and if the survey result still holds true
what is the probability that exactly 19 are very satisfied with their primary financial institution? What
distribution would you use for analysis & why?**

In [5]:
#We use binomial and pmf here to get values for a discrete point
import scipy
import numpy as np
from scipy.stats import binom

In [6]:
print(binom.pmf(k=19, n=25, p=0.65))

0.09077799859322791


**Question 2:According to Indian Census Bureau, approximately 6% of all workers in Ludhiana Punjab are
unemployed. In conducting a random telephone survey in Ludhiana, what is the probabilty of getting two or
fewer unemployed workers in a sample of 20. Comment (PMF or PDF or CDF)**

In [7]:
#Here cdf with binomial will be required for continuous graph
binom.cdf(2,20,0.06)

0.8850275957378545

**Question 3 : Suppose bank customers arrive randomly on a weekday afternoon at an average of 3.2 customers
every 4 mins. What is the probability of exactly 5 customers arriving in a 4 minute interval on a weekday
afternoon**


In [8]:
#If emphasis on number of events with fixed time then its poisson distribution
#GO TO LAST QUESTION
#pmf
from scipy.stats import poisson
poisson.pmf(5,3.2) #x,mean

0.11397938346351824

**Question 4 : Bank customers arrive randomly on weekday afternoons at an average of 3.2 customers every 4 mins. What is the probability of having more than 7 customers in a 4 minute interval on a weekday afternoon?**

In [9]:
prob=poisson.cdf(7,3.2)

In [10]:
#We use cdf when we want to find probab of any atleast factor. 
#Since we need more than 7 customers ka probab we can use 1-cdf
prob_morethan_1= 1-prob
print(prob_morethan_1)

0.01682984174895752


**Question 5: A bank has an average random arrival rate of 3.2 customers every 4 minutes. What is the
probability of getting exactly 10 customers during an 8 min interval?**


In [11]:
poisson.pmf(10,6.4)

0.052790043854115495

**Question 6:. Suppose the amount of time it takes to assemble a plastic module ranges from 27 - 39 seconds and that assembly times are uniformly distributed. Describe the distribution. What is the probabilty that a given assembly wll take between 30 & 35 seconds?**

In [14]:
#Uniform distribution
#cdf -- between something
#when uniform pdf and pmf cannot be used coz both will have same/uniform/constant values and hence will result in 0
U=np.arange(27,40,1)
U
#ordered array arranging

array([27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [15]:
from scipy.stats import uniform

In [16]:
uniform.mean(loc=27,scale=12)
#loc is start point and scale is the end point

33.0

In [19]:
uniform.cdf(np.arange(30,36,1), loc=27,scale=12)
#finding the cdf of each from 30 to 35 (n-1)

array([0.25      , 0.33333333, 0.41666667, 0.5       , 0.58333333,
       0.66666667])

In [23]:
FINAL_PROBAB=0.66666667-0.25
FINAL_PROBAB

0.41666667

In [20]:
uniform.pdf(np.arange(30,36,1), loc=27,scale=12)

array([0.08333333, 0.08333333, 0.08333333, 0.08333333, 0.08333333,
       0.08333333])

In [21]:
uniform.pdf(np.arange(30,35,1), loc=27,scale=12)

array([0.08333333, 0.08333333, 0.08333333, 0.08333333, 0.08333333])

**Question 7:Acc to National Association of Insurance Commissioners, average annual cost for automobile
insurance in India was Rs 691. Suppose automobile insurance costs are uniformly distributed with a range of
Rs. 200 to Rs. 1182. What is the standard deviation of this uniform distribution.**

In [24]:
uniform.mean(loc=200,scale=982)

691.0

In [25]:
uniform.std(loc=200,scale=982)

283.4789821721062

**Question 8: What is the probability of getting a score greater than 700 on a GMAT test that has a mean of 494
and STD of 100? Assume GMAT scores are normally distributed? For the same GMAT exam, what is the
probabilty of randomly drawing a score that is 550 or less? What is the probabilty of randomly obtaining a
score between 300 and 600 on the same exam? What is the probabilty of randomly obtaining a score
between 350 and 450 on the same exam?**

In [37]:
from scipy.stats import norm
val,m,s =67,65.5,2.5
print(norm.cdf(val,m,s))
val1,m,s =66,65.5,2.5
print(norm.cdf(val1,m,s))
val2,m,s =65.6,65.5,2.5
print(norm.cdf(val2,m,s))
val3,m,s =65.4,65.5,2.5
print(norm.cdf(val3,m,s))
val4,m,s =63,65.5,2.5
print(norm.cdf(val4,m,s))

0.7257468822499265
0.579259709439103
0.5159534368528299
0.48404656314717015
0.15865525393145707


*What is the probability of getting a score greater than 700 on a GMAT test that has a mean of 494 and STD of 100? Assume GMAT scores are normally distributed?*

In [38]:
print(1-norm.cdf(700,494,100))

0.019699270409376912


*For the same GMAT exam, what is the probabilty of randomly drawing a score that is 550 or less?*

In [39]:
print(norm.cdf(550,494,100))

0.712260281150973


*What is the probabilty of randomly obtaining a score between 300 and 600 on the same exam?*

In [40]:
print(norm.cdf(600,494,100)- norm.cdf(300,494,100))

0.8292378553956377


*What is the probabilty of randomly obtaining a score between 350 and 450 on the same exam?*

In [41]:
print(norm.cdf(450,494,100)- norm.cdf(350,494,100))

0.2550348541262666


**Question 9:Suppose 18 major computer companies operate in India and 12 are located in Hyderabad. If three
companies are selected randomly from the entire list what is the probability that one or more selected
companies are located in Hyderabad**

In [ ]:
#Hyper geom function instead of binomial 
#When sampling is done without replacement, the
# trials are not independent as probability of each
# successive event is dependent on previous hence
# we cannot use Binomial Distribution, as in both
# cases(Binom & Hypergeom) remember there will be
# 2 outcomes (success or failure) so the choice of
# distribution is very imp.
#population=18,success index=12,variable=1 or more should be in hyderabad

In [5]:
from scipy.stats import hypergeom
pval=hypergeom.sf(0,18,3,12)
pval

0.9754901960784306

0.9754901960784306

**Question 10:In Mumbai 18 police officers are eligible for promotion. 11 of the 18 are women. Suppose only 5 officers are chosen for promotion. If the officers chosen for promotion had been selected by chance alone, what is the probability that one or fewer of five promoted officers would be women?**

In [ ]:
#Hyper geom function instead of binomial 
#When sampling is done without replacement, the
# trials are not independent as probability of each
# successive event is dependent on previous hence
# we cannot use Binomial Distribution, as in both
# cases(Binom & Hypergeom) remember there will be
# 2 outcomes (success or failure) so the choice of
# distribution is very imp.
#pop=18,survivalindex=1 or more. for survival function always take 1-cdf

In [ ]:
from scipy.stats import hypergeom
pval2=hypergeom.cdf(1,18,5,11)
pval2

**Question 11: A manufacturing firm has been involved in a statistical quality control for several years. As part of
the production process, parts are randomly selected and tested. From records of tests it has been established
that a defective part occurs in a pattern that is Poisson distributed on the average of 1.38 defects every 20
minutes during production run. Use this information to determine the probability that less than 15 mins will
elapse between any 2 defects.**

In [ ]:
#If emphasis on number of events with fixed time limit then its poisson distribution
#this is exponential distribution If emphasis on time with fixed number of events 

In [8]:
mu1=1/1.38
mu1

0.7246376811594204

In [9]:
from scipy.stats import expon
expon.cdf(0.75,0,(1/1.38)) #15/20=0.75

0.6447736190750485